{"name": "test_summary", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: Failed User Agents: [('Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.77 Mobile/15E148 Safari/604.1', 'browser', 'Chrome', 'No'), ('Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', 'platform', 'Googlebot', 'Unknown'), ('Mozilla/5.0 (iPad; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'device', 'iPhone', 'Unknown')]\nassert 3 == 0\n +  where 3 = len([('Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.77 Mobile/15...X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'device', 'iPhone', 'Unknown')])\n +    where [('Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.77 Mobile/15...X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'device', 'iPhone', 'Unknown')] = <tests.test_user_auth.TestUserAuth object at 0x000002B9FA408ED0>.failed_agents", "trace": "self = <tests.test_user_auth.TestUserAuth object at 0x000002B9FA408ED0>\n\n    @allure.description(\"Final test to check if there were any identification errors for User Agents\")\n    @pytest.mark.xfail\n    def test_summary(self):\n        \"\"\"\n        Итоговый тест, который проверяет, были ли ошибки в определении User Agent\n        \"\"\"\n>       assert len(self.failed_agents) == 0, f\"Failed User Agents: {self.failed_agents}\"\nE       AssertionError: Failed User Agents: [('Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.77 Mobile/15E148 Safari/604.1', 'browser', 'Chrome', 'No'), ('Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)', 'platform', 'Googlebot', 'Unknown'), ('Mozilla/5.0 (iPad; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'device', 'iPhone', 'Unknown')]\nE       assert 3 == 0\nE        +  where 3 = len([('Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.77 Mobile/15...X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'device', 'iPhone', 'Unknown')])\nE        +    where [('Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/91.0.4472.77 Mobile/15...X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1', 'device', 'iPhone', 'Unknown')] = <tests.test_user_auth.TestUserAuth object at 0x000002B9FA408ED0>.failed_agents\n\ntests\\test_user_auth.py:154: AssertionError"}, "description": "Final test to check if there were any identification errors for User Agents", "start": 1697058825390, "stop": 1697058825390, "uuid": "4f4a63c5-5e2e-447a-b3ac-de0c78497913", "historyId": "60e3e602e149baf1e578e11e95f1fb22", "testCaseId": "60e3e602e149baf1e578e11e95f1fb22", "fullName": "tests.test_user_auth.TestUserAuth#test_summary", "labels": [{"name": "epic", "value": "Authorization cases"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "LAPTOP-SFQ2DO00"}, {"name": "thread", "value": "17712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}]}